ALTER TABLE products
  ADD COLUMN IF NOT EXISTS price INTEGER,
  ADD COLUMN IF NOT EXISTS old_price INTEGER,
  ADD COLUMN IF NOT EXISTS img TEXT,
  ADD COLUMN IF NOT EXISTS tag TEXT,
  ADD COLUMN IF NOT EXISTS angle_type TEXT,
  ADD COLUMN IF NOT EXISTS fabric JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS colors JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS sku TEXT;
